---
- name: Ensure that tower job_status directory exists.
  file:
    group: awx
    mode: 0755
    owner: awx
    path: "{{ restore_awx_home }}/job_status"
    state: directory

- name: Restore job stdout
  shell: rsync -aq {{ backup_dir.rstrip("/") }}/restore/job_status/ {{ restore_awx_home }}/job_status/
