---
- name: Ensure that tower projects directory exists.
  file:
    group: awx
    mode: 0755
    owner: awx
    path: "{{ restore_awx_home }}/projects"
    state: directory

- name: Restore manual projects
  shell: rsync -aq {{ backup_dir.rstrip("/") }}/restore/projects/ {{restore_awx_home}}/projects/
