---
- include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_os_family }}.yml'
        - 'default.yml'
      paths: '../vars'

- name: Place the security configuration file
  template:
    dest: '{{ redis_conf_path }}/{{ redis_conf_filename }}'
    force: yes
    group: redis
    mode: 0640
    owner: redis
    src: redis.conf.j2
  when: "redis_conf_password is defined and redis_conf_password != ''"
  register: result

- name: Ensure that Redis is running.
  service:
    name: '{{ redis_service_name }}'
    state: started
    enabled: yes

- name: If the Redis configuration was changed, reload Redis immediately.
  service:
    name: '{{ redis_service_name }}'
    state: restarted
  when: result.changed
