---
- hosts: primary
  gather_facts: yes
  roles:
    - role: check_config_static
    - role: config_dynamic
    - role: restore
      restore_database: "{{ config_dynamic_database }}"
      restore_pg_database: "{{ pg_database }}"

